### ISSUE TITLE
reduce runoff cap?

### ISSUE THREAD

**Issue by aekiss** [pedrocol/basal_mom5-collaborative-project#10]
YAML spreads out the runoff to keep the mass flux below a cap which is set by trial and error to avoid numerical instability (eg negative salinity). 

This cap defaults to 0.03kg/m^2/s but can vary spatially as specified in `atm.nml` via `num_runoff_caps`, `runoff_caps`, `runoff_caps_is`, `runoff_caps_ie`, `runoff_caps_js`, `runoff_caps_je` in group `runoff_nml`.

I wonder whether we can reduce the horizontal spreading in regions where we distribute over depth? That would be more realistic for the basal melt, but less realistic for icebergs (though we could treat the iceberg runoff separately if we switch to JRA55-do v1.4 or later).

**Comment by aekiss** [comment]
The first thing to check is whether the runoff in JRA55-do ever gets as large as 0.03kg/m^2/s around Antarctica. If not, there's no point increasing the cap.

**Comment by pedrocol** [comment]
I checked the runoff output from the control run and we do have some values reaching 0.03kg/m^2/s (maximum runoff value), in very specific locations though

![Screenshot from 2022-08-01 21-36-20](https://user-images.githubusercontent.com/23285319/182272008-2d0880c3-3864-4d00-983e-fc7ac0b9082a.png)

**Comment by aekiss** [comment]
Interesting. How big does it get in the input runoff?

**Comment by aekiss** [comment]
(this issue is a low priority, BTW)

**Comment by pedrocol** [comment]
In the input runoff the maximum value is 0.4:
![Screenshot from 2022-08-02 21-41-56](https://user-images.githubusercontent.com/23285319/182500231-12b9e94b-b6fd-42d3-a7a7-8bac7c5560fe.png)
But, we have values larger than 0.3 only in that grid point
![Screenshot from 2022-08-02 21-42-17](https://user-images.githubusercontent.com/23285319/182500234-035dc826-6663-4de6-b2a0-ae9e7295937c.png)

**Comment by aekiss** [comment]
is that the global max or the Antarctic?

**Comment by pedrocol** [comment]
That was global, sorry. In the case of the Antarctic region the max values is 0.0044
![Screenshot from 2022-08-02 22-05-57](https://user-images.githubusercontent.com/23285319/182502334-4cae6fef-0867-4201-ba9d-ba815786edd4.png)

**Comment by pedrocol** [comment]
First issue closed, this feels nice. Thanks Andrew!
