### ISSUE TITLE
Enhanced parameterised vertical mixing of runoff

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#11]
@pedrocol could you also clarify for me how the vertical mixing of the basal melt works? I think usually the extra vertical mixing of runoff is applied to keep the model stable (i.e. spreading out the runoff over depth). But if we're already putting the basal melt spread over depth, do we want to apply this extra vertical mixing or not?

**Comment by aekiss** [comment]
The IAF configs insert river runoff over the top 40m rather than using diffusion - e.g. see
https://github.com/COSIMA/01deg_jra55_iaf/blob/master/ocean/input.nml#L284-L291
```
&ocean_rivermix_nml
    river_diffuse_salt = .true.
    river_diffuse_temp = .true.
    river_diffusion_thickness = 0.0
    river_diffusivity = 0.0
    river_insertion_thickness = 40.0
    use_this_module   = .true.
/
```

**Comment by adele157** [comment]
Ah, cool. Looks like that's the same with the RYF case we're using here. So no need to worry about extra mixing being applied to the basal melt then.

**Comment by aekiss** [comment]
If we split basal and calving we'd need to set `discharge_combine_runoff_calve=.false.` and set `runoff_insertion_thickness` and `calving_insertion_thickness` rather than `river_insertion_thickness` - see https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_param/sources/ocean_rivermix.F90

**Comment by aekiss** [comment]
With combined runoff, do we need to be careful how @pedrocol's code interacts with `river_insertion_thickness`?

**Comment by pedrocol** [comment]
There is one extra treatment of the vertical mixing related with runoff/basal in /home/552/pc5520/access-om2/src/mom/src/mom5/ocean_param/vertical/ocean_vert_kpp_mom4p1.F90

There is an increase of the kinematic surface temperature/salinity (wsfc), but since basal goes always at depth, it shouldn't be there (I just realized). I'm changing the code accordingly

**Comment by pedrocol** [comment]
@aekiss I agree that since we won't having a runoff field the combined runoff/calving is no longer needed. But there is no harm on using it, in the end it will be river=calving. The basal code works independently
