### ISSUE TITLE
Offline interp of calving and import to MOM5

### ISSUE THREAD

**Issue by pedrocol** [pedrocol/basal_mom5-collaborative-project#12]

**Comment by aekiss** [comment]
following on from https://github.com/pedrocol/basal_mom5-collaborative-project/issues/1#issuecomment-1201806919

**Comment by pedrocol** [comment]
Since we will importing the interpolated calving field in the MOM5 code, I'ĺl change the title

**Comment by aekiss** [comment]
Did you mean horizontal interpolation to the nearest ocean point? For river runoff that's actually done by libaccessom2 - see 
https://github.com/COSIMA/libaccessom2/blob/master/atm/src/remap_runoff_mod.F90 
https://github.com/COSIMA/libaccessom2#river-runoff-remapping
but I thought that was already done for both solid and liquid runoff separately before CICE combines them?

**Comment by pedrocol** [comment]
Hi Andrew, we tried to import the calving field with the v1.3 but this was not possible without changing the code. At that point we decided that the easiest way of action was to make an offline interpolation and import the calving field directly in MOM5.
Yesterday Adele proposed to take the calving output of a simulation to avoid doing the interpolation with a new code, so we should just import that output. Have you ever run a 1/10 simulation using the calving field?

**Comment by adele157** [comment]
At what point are the runoff and calving fields combined? In CICE? Or in MOM?

**Comment by pedrocol** [comment]
They are combined in MOM as river = calving + runoff. @aekiss Does CICE makes use of these variables at any point?

**Comment by pedrocol** [comment]
The interpolation and import is ready.

In the first upper plot we can see the ratio between calving and runoff for the original data. In the plot below we can see the ratio between the output runoff (control) and the output calving. To output the calving in the 1/10 model grid, I replaced the runoff file with other file with the same structure but filled with the calving values. Both plots look very similar, so the calving field was correctly imported and interpolated. 

![Screenshot from 2022-09-17 01-25-58](https://user-images.githubusercontent.com/23285319/190866603-15ae98ee-7c5f-4e68-8fc2-6392c916cac8.png)

Once I had the calving field in the 1/10 grid, I made the import of this field in ocean_sbc. Below the ratio between the new output and the previous output. They are both the same, and therefore the field is correctly imported as an independent file.

![Screenshot from 2022-09-17 13-21-50](https://user-images.githubusercontent.com/23285319/190866606-9528c72c-ced8-45b2-a11c-45d5421c98cb.png)

**Comment by pedrocol** [comment]
I got a better way to validate this. I added up the calving and the basal arrays for the whole domain, and I compared this value to the runoff value of the control simulation, and I got 0.99999994. So the calving interpolation result is fine in terms of total amount, and also in terms of geographic distribution (previous plots). I'm closing the issue
