### ISSUE TITLE
Use of older restarts with latest version of accesom2

### ISSUE THREAD

**Issue by pedrocol** [pedrocol/basal_mom5-collaborative-project#13]
copied from https://github.com/pedrocol/basal_mom5-collaborative-project/issues/1#issuecomment-1205921238:

Errors when using easterlies run restarts on the latest version of the code. Some comments:
"""
If I remember well and I'm not wrong, I think the newer version of the code uses more tracers (co2? maybe) than the previous version, and the restarts don't have these fields.

forrtl: error (78): process killed (SIGTERM)
Image PC Routine Line Source
fms_ACCESS-OM-BGC 0000000001CACBA4 Unknown Unknown Unknown
libpthread-2.28.s 000014592E5AFC20 Unknown Unknown Unknown
libuct_ib.so.0.0. 0000145913030697 Unknown Unknown Unknown
libucp.so.0.0.0 0000145914C20E9A ucp_worker_progre Unknown Unknown
mca_pml_ucx.so 00001459150C8397 mca_pml_ucx_progr Unknown Unknown
libopen-pal.so.40 00001459298BB72B opal_progress Unknown Unknown
libmpi.so.40.20.2 000014592EB8E2D5 ompi_request_defa Unknown Unknown
libmpi.so.40.20.2 000014592EBD113F PMPI_Waitall Unknown Unknown
libmpi_mpifh.so 000014592EEC67ED Unknown Unknown Unknown
fms_ACCESS-OM-BGC 0000000001B48A00 Unknown Unknown Unknown
fms_ACCESS-OM-BGC 0000000001B479B9 Unknown Unknown Unknown
fms_ACCESS-OM-BGC 0000000001A55993 mod_oasis_advance 1130 mod_oasis_advance.F90
fms_ACCESS-OM-BGC 0000000001957178 mod_oasis_getput_ 760 mod_oasis_getput_interface.F90
fms_ACCESS-OM-BGC 0000000000411BCC mom_oasis3_interf 688 mom_oasis3_interface.F90
fms_ACCESS-OM-BGC 00000000004239A8 MAIN__ 637 ocean_solo.F90
fms_ACCESS-OM-BGC 000000000040F6A2 Unknown Unknown Unknown
[libc-2.28.so](http://libc-2.28.so/) 000014592E1FB493 __libc_start_main Unknown Unknown
fms_ACCESS-OM-BGC 000000000040F5AE Unknown Unknown Unknown
forrtl: error (78): process killed (SIGTERM)
"""

From Andrew Kiss
> There are now 2 types of ACCESS-OM2 MOM executables, one including BGC (`fms_ACCESS-OM-BGC_*_libaccessom2_*.x`, which is what you tried to use), and one without (`fms_ACCESS-OM_*_libaccessom2_*.x`). If I recall correctly, a non-BGC executable won't need extra fields in the restarts. You can build the non-BGC version by setting `export mom_type=ACCESS-OM` in install.sh

**Comment by adele157** [comment]
Can we close this issue?

**Comment by pedrocol** [comment]
Since we are importing the calving field directly in MOM I think this is no longer needed. Just as a reminder, we decided to keep with version 1.3 for comparison ends
