### ISSUE TITLE
Hovmollers of T-S-\rho anomalies

### ISSUE THREAD

**Issue by matthew-england-unsw** [pedrocol/basal_mom5-collaborative-project#14]
Would be great to analyse time-evolving vertical structure of the hydrographic anomalies: as Hovmöller plots going forward in time (x-axis) vs depth in y-axis.    For T, S and density.

**Comment by pedrocol** [comment]
Matt, this would be for single (lon,lat) points right? Normally a relevant point near the coast for a couple ice-shelves, I'm correct?

**Comment by adele157** [comment]
Probably averaged over particular regions on the shelf would make sense. We could look at the [maps of temperature change](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/5) and pick the regions to average over based on where the cooling/warming signals are.

**Comment by matthew-england-unsw** [comment]
Yes some area-averages in key locations would be best.   
Areas could be determined by looking at maps of T change as Adele suggests.
In some cases we should localise this average to be a region right up against the shelf, to see T-S evolution there as a function of basal melt depth vs. MLD variations etc.  To check how this plays out in time....?

**Comment by pedrocol** [comment]
I've chosen two locations, one with large change in bottom temperature (Amundsen) and another one with small change (Wedell). Both limited by the shelf and two values of longitue
![Screenshot from 2022-08-22 23-05-06](https://user-images.githubusercontent.com/23285319/186052802-e77b9259-78f4-43ef-8d77-55776728a9e0.png)

Results for Wedell
![Screenshot from 2022-08-22 23-04-47](https://user-images.githubusercontent.com/23285319/186052952-f5c7aa85-2c33-49ba-a409-cb1fc01fd90a.png)

The change in T at the surface is probably coming for the smaller amount of runoff at the surface (now there is only 50% in the form of calving) that was heating the ocean (only in winter though). The salinity values for control look very small, perhaps there is a not working mask that is adding zeroes in the average...

Results for Amundsen
The effect on the Amundsen sea looks to be very important, something that we have seen on the previous plots
![Screenshot from 2022-08-22 23-08-00](https://user-images.githubusercontent.com/23285319/186053053-f3141fbe-5042-4d79-9efc-ed617e45767b.png)

**Comment by adele157** [comment]
Yes, the 0 values at depth in the control look suspicious. Where's the code?

**Comment by pedrocol** [comment]
Here is the code https://github.com/pedrocol/basal_mom5-collaborative-project/blob/main/notebooks/TSrho_anom_hovmo/TS_anom_hovmo.ipynb

I obtained the mask from the volume array, in the following way
volume = area_t*thickness
mask = volume * 0 +1

**Comment by adele157** [comment]
Closing, uses old simulations. New issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/34).
