### ISSUE TITLE
Comparison with observations

### ISSUE THREAD

**Issue by pedrocol** [pedrocol/basal_mom5-collaborative-project#18]
Anyone know any dataset to compare with? (surface temp/salt/sea-ice)

**Comment by adele157** [comment]
I'd suggest the [Pathenet et al. 2021 climatology](https://zenodo.org/record/4071906#.YwWmKJNBxqs) for upper ocean temp/salt. It is better than Schmidtko et al. 2014, because it includes the seal data also. 

@aekiss can probably comment on what is best for sea ice obs, but perhaps check what was used in Kiss et al. 2020 and do something similar?

**Comment by aekiss** [comment]
I've compared `aice` to NSIDC sea ice concentration data from http://nsidc.org/data/G02202, which is downloaded here `/g/data3/hh5/tmp/cosima/observations/NOAA/G02202_V3`

Sea ice thickness obs are much harder to get, so I've used GIOMAS reanalysis instead. Not sure how good it is.

There are routines for loading these here
https://nbviewer.org/github/aekiss/ice_analysis/blob/main/ice_maps.ipynb#Define-data-loaders
and regridders here
https://nbviewer.org/github/aekiss/ice_analysis/blob/main/ice_maps.ipynb#Regridders

**Comment by aekiss** [comment]
There are some observational estimates of thickness but I haven't used them (yet)
- http://dx.doi.org/10.1016/j.dsr2.2010.12.001
- http://dx.doi.org/10.1029/2007JC004254
- https://doi.org/10.5194%2Ftc-14-4453-2020
-  http://aspect.antarctica.gov.au/data (might be biased toward thin ice where ships go)

**Comment by aekiss** [comment]
relevant to T/S plots https://www.nature.com/articles/s41467-022-28751-5
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019JC015133

**Comment by hrsdawson** [comment]
Figure showing comparison of upper ocean (10-380m) temperature (top) and salinity (bottom) to observations from Pauthenet et al. (2021). I've only plotted the control and GPC008 (_meltwater temp equal to  min(Tfreezing(s=0),Tinsitu)_) here. Overall, very similar spatial pattern in anomalies. GPC008 is slightly colder in the outer Amundsen Sea shelf region than the control, which makes is closer to obs. Also slightly fresher than control between the Amundsen and Ross Seas (again closer to obs overall I think), and slightly saltier than control along the inner Weddell Sea shelf. 

<img width="1380" alt="Screen Shot 2022-09-22 at 4 32 39 pm" src="https://user-images.githubusercontent.com/62230733/191675543-6fc8b453-6d29-4329-991d-7afca3af743a.png">

**Comment by pedrocol** [comment]
I performed a comparison with the data of the Antarctic sea-ice extent (https://earthobservatory.nasa.gov/world-of-change/sea-ice-antarctic)

And I noticed that the control simulation compares very well with observations:
![seaice_ext_con](https://user-images.githubusercontent.com/23285319/192933433-4105d41e-dfd8-4b0b-86d9-e26e8d17d902.png)
![seaice_ext_obs](https://user-images.githubusercontent.com/23285319/192933440-cb40e60a-3fa3-457f-a249-01a154a7916b.png)
Not the case for Tfreezing_min_s0
![seaice_ext_Tmin](https://user-images.githubusercontent.com/23285319/192933445-ae76d019-e99c-493e-81fa-a877e13fffb0.png)

I was wondering if the namelist parameters in CICE were set considering this diagnostic, perhaps we need to set other namelist parameters in order to adjust the amount of sea-ice present in the simulations that the runoff is removed from the surface

**Comment by adele157** [comment]
Interesting! Yes there has no doubt been tuning done in CICE to match the
sea ice with observations. @Andrew Kiss ***@***.***> would know
the details.

**Comment by aekiss** [comment]
I've done a lot of experiments with different CICE parameters, but they don't affect the SIC bias much - see https://accessdev.nci.org.au/trac/attachment/wiki/ThursProg/14.Andrew_Kiss_ACCESS_science_days_2021.pdf

I came to the conclusion that SIC biases are mostly due to biases in the JRA55-do forcing: https://github.com/COSIMA/access-om2/issues/242#issuecomment-1029573192

**Comment by aekiss** [comment]
My experiments are in `/home/156/aek156/payu/param_ensemble`.
Tables of perturbed parameters are in `/home/156/aek156/payu/param_ensemble/access-om2*/ensemble/ensemble.yaml`

**Comment by adele157** [comment]
Closing as this uses old simulations. New issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/37).
