### ISSUE TITLE
Heat fluxes

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#2]
Plot the heat fluxes from runoff in the different runoff setups to see what impact the different formulations have (maps and time series). Also quantify the differences between the different setups compared to the total heat budget on the shelf.

**Comment by PaulSpence** [comment]
I took a quick look at some "sfc_hflux" terms, but get mostly 0 between simulations. e.g.:
Gade_ib = cc.querying.getvar(Tfreezing_min_calv_2_gade_ib, 'total_ocean_calving_heat', basal_session,frequency='1 monthly',start_time=start_time, end_time=end_time,decode_coords = False)
Gade_ib.plot()

![Screen Shot 2023-03-09 at 2 50 26 pm](https://user-images.githubusercontent.com/6644956/223912152-0e8668be-b767-471c-be90-0d0f3020d0ff.png)

**Comment by adele157** [comment]
I'm plotting these at the moment too! Will post some figures shortly.

**Comment by PaulSpence** [comment]
![Screen Shot 2023-03-09 at 2 53 43 pm](https://user-images.githubusercontent.com/6644956/223912585-274b04bb-6249-4f29-85a3-13aca9d09a57.png)

**Comment by adele157** [comment]
This is averaged over years 6-7:

<img width="890" alt="Screen Shot 2023-03-09 at 2 55 19 pm" src="https://user-images.githubusercontent.com/8506963/223912923-63cb42ef-6dd7-4471-9bbc-3967d95d2cb8.png">

<img width="890" alt="Screen Shot 2023-03-09 at 2 55 29 pm" src="https://user-images.githubusercontent.com/8506963/223912930-c157463c-3bc2-446b-8e01-7096c18a190f.png">

Overall less cooling from the atmosphere/ice in the basal and iceberg runs. This comes from both changes in the coupler term (shortwave, longwave, evap, sensible) and sea ice (frazil). I'll do another plot splitting up the coupler term.

**Comment by PaulSpence** [comment]
Is that from these terms: "total_ocean_calving_heat",total_ocean_hflx_coupler" etc.?

**Comment by adele157** [comment]
Terms are (in order plotted above): sfc_hflux_from_runoff, sfc_hflux_coupler, sfc_hflux_pme, frazil_3d_int_z, temp_basalmix, temp_icbmix

**Comment by PaulSpence** [comment]
I got tricked by terms like, "sfc_hflux_from_calving"

**Comment by adele157** [comment]
I have hit a problem now though trying to split up the coupler heat flux. I was expecting:

`sfc_hflux_coupler = swflx + lw_heat + sens_heat + evap_heat + fprec_melt_heat`

But it's not equal to the sum of those terms. @aekiss any hints? `calving_melt_heat = 0` right?

**Comment by adele157** [comment]
Ok, think I found the missing term. https://github.com/COSIMA/access-om2/issues/139

**Comment by adele157** [comment]
The extra heat flux term that comes through the coupler in ACCESS-OM2 is `mh_flux`, which is associated with the mass flux of sea ice melt/formation. We don't have `mh_flux` saved though. I guess we can calculate it as a residual:
`mh_flux = sfc_hflux_coupler - (swflx + lw_heat + sens_heat + evap_heat + fprec_melt_heat)`

**Comment by adele157** [comment]
There are changes in many components! This is the same as above, but with the coupler term split up further.

<img width="890" alt="Screen Shot 2023-03-09 at 3 45 18 pm" src="https://user-images.githubusercontent.com/8506963/223919671-d146b86f-8083-4c03-a34f-9e82a6af4a2a.png">

**Comment by adele157** [comment]
Closing as this uses old simulation data. New issue on heat fluxes is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/66).
