### ISSUE TITLE
Bottom age

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#20]
Plot bottom age.

The story as we left it 2 weeks ago is:
- [surface water mass transformation (i.e. DSW formation) increases](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/8#issuecomment-1225158191). 
- But this conflicts with the change in bottom temperature, which mostly [warms in the abyss](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/5#issuecomment-1211459054).

A proposed solution to these seemingly conflicting responses is if DSW formation at the surface increases (because there is less freshwater input at the surface and therefore the water column is less stratified and easier to convect), but then there is so much mixing of these dense waters over the continental shelf that they end up too light to overflow. Bottom age should tell us how the abyssal ventilation is changing.

**Comment by pedrocol** [comment]
Below a plot of the age difference between a basal melt run and the control run. 

![Screenshot from 2022-09-07 16-32-28](https://user-images.githubusercontent.com/23285319/188962010-4c0a922b-03bc-4f6f-9bed-35701f8c9ece.png)

Abyssal waters in the basal melt run are older, this means that the overflows are weaker, which is very likely due to the change of the stratification on the shelf (lighter water in the presence of runoff at depth)

**Comment by adele157** [comment]
Excellent, this is good to see our hypothesis is correct. 

It's difficult to tell what is happening in the Weddell though - older water on the main outflow path on the slope (between the 1000m and 3000m isobaths), but there's younger water on the northern edge of the gyre. 

Another plot with a larger colourbar range to focus on the shelf response would be helpful too - it looks like it's mostly blue on the shelf, which would be consistent with more mixing.

**Comment by pedrocol** [comment]
I doubled the range. The younger water on the northern edge may be coming from the melting of sea-ice

![Screenshot from 2022-09-07 18-00-29](https://user-images.githubusercontent.com/23285319/188978421-32b44c6c-6c5c-4976-81a8-224f50bb6578.png)

**Comment by pedrocol** [comment]
Perhaps distributing the fresh water between 200m and 1000m might not be a good idea in this region. Maybe changing the input depth between 200m and say 400m might limit the effect on the overflow

**Comment by adele157** [comment]
I think it would be better to make the parameterisation physically justified, if that means that the overflows decrease that's ok. I think we should be a little wary of tuning the parameterisation to get the answer that we want. 

In the Weddell, I think if we do the correct calving / basal split of the runoff that should help a lot, because the Weddell is mostly calving dominated, so we're putting too much runoff at depth at the moment.

**Comment by adele157** [comment]
Closing this issue because it uses old simulations. See new issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/29).
