### ISSUE TITLE
cross-contour transport

### ISSUE THREAD

**Issue by claireyung** [pedrocol/basal_mom5-collaborative-project#22]
Compute cross-contour transport at different density classes to see if there are circulation changes.

**Comment by claireyung** [comment]
I've calculated the cross-contour transport in sigma_1 classes for the five years of the GPC008 perturbation. The contour is the 1000m isobath
![contour](https://user-images.githubusercontent.com/61528379/194693074-8f077c12-3671-4cab-9def-41076f11c67b.png)

The circumpolar integral of the transport, cumulatively integrated from densest to lightest is like the overturning streamfunction across the contour:
![offshore_transport_sum](https://user-images.githubusercontent.com/61528379/194693346-ad499984-9c4c-4cc1-a089-cc8741261022.png)
The main change due to the perturbation is that the dense water export decreases a little over time, but there is also a very fast change to have more southward transport around sigma_1 = 32.3 which pops up in the first year.

To investigate the spatial distribution, we can also plot the transport integrated vertically over all densities, and cumulatively summed along the contour from west to east (it's very noisy if you don't do this).
![transport_cumsum](https://user-images.githubusercontent.com/61528379/194693480-bf0c06ca-f45f-44b6-9b01-2c061d172041.png)
The main regions where the transport differs is immediately west of when the lines get separated (due to the cumulative sum). To my eye, the main regions are just west of the Ross around 170W, and in the Amundsen area. Everything else seems pretty similar, though I suppose the integration over all densities would disguise differences in WMT/mixing.

If anyone has any ideas of other metrics to plot please let me know!

**Comment by adele157** [comment]
Closing due to old simulation data. See new issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/28).
