### ISSUE TITLE
Choice of T/S properties for basal melt input

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#24]
Pedro has tried a bunch of different formulations for the input temperature of the basal melt, as follows:
<img width="500" alt="Screen Shot 2022-09-08 at 10 41 44 am" src="https://user-images.githubusercontent.com/8506963/189008788-746a65ff-0c8e-4b72-978e-eb849dc7747c.png">

These all have 0 salinity for the freshwater going in. How do these different formulations compare and which is most physically justified?

**Comment by adele157** [comment]
There seems to be little dependence on the input temperature of the basal melt.

Here is bottom temperature comparison for the first 3 formulations, averaged over the 2 years of simulation:
![Screen Shot 2022-09-08 at 10 50 08 am](https://user-images.githubusercontent.com/8506963/189012637-aa3b220f-15df-4aff-85a3-3de3f9fa430b.jpg)

And here is depth average temperature over the whole shelf:
<img width="500" alt="Screen Shot 2022-09-08 at 10 50 38 am" src="https://user-images.githubusercontent.com/8506963/189012761-f65a3746-21de-48c0-894b-13a12e481d31.png">

And depth average salinity over the shelf:
<img width="500" alt="Screen Shot 2022-09-08 at 10 50 55 am" src="https://user-images.githubusercontent.com/8506963/189012797-e0ab02f4-3e22-4b71-81b8-7af8f6acc784.png">

Given there is very little dependence on the temperature formulation, it seems like a good idea to proceed with whichever formulation is most physically justified.

@pedrocol do you want to add the derivation of your suggested new formulation here?

**Comment by pedrocol** [comment]
As discussed

![Screenshot from 2022-09-07 22-26-22](https://user-images.githubusercontent.com/23285319/189013226-de881da7-2701-43ce-8f9f-12adf31eb8ab.png)

Where, S_R is the resulting salinity, S_i insitu salinity, q fresh water flux, T_R resulting temperature, gamma thermal exchange coefficient (normally 10^-4). The first equation is a salt balance. The second equation uses S_FW = 0. In the third equation I reorganize the terms and I equal it to the latent heat due to melting/freezing. The fourth equation leaves a expression for T_R, which is the T_FW plus (melting, minus is freezing) an additional term due to ice melting (\Delta S is positive)

**Comment by pedrocol** [comment]
The previous scheme had a tuning parameter (\gamma) that comes from the Grosfeld 1997 parameterization. @bkgf proposed a different scheme based on following the Gade line. 
![Screenshot from 2022-09-17 13-34-24](https://user-images.githubusercontent.com/23285319/190867271-87acd89e-0dfb-4f38-a673-1be611c390ea.png)

![Compare_MOM5_v_gade_dT_given_dS_GaltonFenzi_20220830](https://user-images.githubusercontent.com/23285319/190867247-9217a63f-0736-4318-9212-5f583c67e2ca.png)[height=0.4]

**Comment by StephenGriffies** [comment]
Sorry to be pedantic: is T  the potential temperature as listed on the vertical axis, or in situ temperature, as typically assumed by those formulating these parameterizations of melt near ice shelves?  

I also re-emphasize the need for us to be converting expressions to the Conservative Temperature used in ocean models (such as ACCESS) and as is now conventional in the ocean literature as per McDougall's work.  These details do matter when concerned with melt.

**Comment by adele157** [comment]
Gade line formulation wins!
