### ISSUE TITLE
Cross-slope volume transport

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#28]
Compute the cross-1000m isobath transport. Plots:
- circumpolar integrated transport, cumulatively integrated as a function of density from bottom up
- time series of maximum offshore transport in dense layers
- transport distribution along the contour in different density classes (DSW, CDW, AASW)

Note, the old issue with the old simulations is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/22).

**Comment by claireyung** [comment]
**Across the 1000 isobath contour:**
<img width="702" alt="Screen Shot 2022-10-24 at 10 29 06 pm" src="https://user-images.githubusercontent.com/61528379/197516030-3c6742fe-14b2-41fe-bfd2-8b389b29a209.png">

**Circumpolar Integrated Transport**

The circumpolar integrated transport, cumulatively integrated as a function of density from bottom up is 
<img width="651" alt="Screen Shot 2022-10-24 at 10 29 21 pm" src="https://user-images.githubusercontent.com/61528379/197516106-15a3fcdd-2241-4297-bcf8-bf58157a90a4.png">
Bottom water export decreases over time, and moves to lighter densities. CDW flows appear to move to heavier densities?

**Time series of bottom water transport**

We can plot the maximum transport of bottom water as a function of time, which is decreasing (though seasonal):
<img width="651" alt="Screen Shot 2022-10-24 at 10 29 35 pm" src="https://user-images.githubusercontent.com/61528379/197516307-c9924d83-83fe-4c83-9d16-a7182b8e1a85.png">

We can also see that the density of this maximum in the streamfunction is decreasing in time (though also seasonal, and dependent on finite sigma_1 bin size)
<img width="651" alt="Screen Shot 2022-10-24 at 10 29 43 pm" src="https://user-images.githubusercontent.com/61528379/197516411-ab61e9eb-7040-4db1-8562-b0eb04454afe.png">

**Cumulative integrals of transport in different density classes**
According to Morrison (2020) paper sigma_1 density classes. Note that the cumulative integrals getting further apart means the transport changed in that location.

**DSW:** Generally decreasing northward transport in source regions, as seen in circumpolar analysis above
<img width="629" alt="Screen Shot 2022-10-24 at 10 29 55 pm" src="https://user-images.githubusercontent.com/61528379/197516719-ab20f5e4-784b-4ba1-a2a0-3e43fa0ff3ed.png">

**CDW:** Generally decreasing southward transport, but increases near 140-100W (cumulative integrals get closer together again) near Amundsen Sea?
<img width="629" alt="Screen Shot 2022-10-24 at 10 30 01 pm" src="https://user-images.githubusercontent.com/61528379/197516782-a30e73c9-e5d5-418d-ab3e-493e349c91c4.png">

**AASW**: Southward transport increasing near Ross?
<img width="629" alt="Screen Shot 2022-10-24 at 10 30 08 pm" src="https://user-images.githubusercontent.com/61528379/197516810-419b8d55-c764-476e-8104-c3d1b212c467.png">

**Vertically integrated heat transport**: Increasing approximately uniformly around the continent
<img width="629" alt="Screen Shot 2022-10-24 at 10 36 16 pm" src="https://user-images.githubusercontent.com/61528379/197516964-4bde02d3-0e82-4007-9718-b7ea947e4be0.png">


See the notebooks in my branch `https://github.com/pedrocol/basal_mom5-collaborative-project/tree/claire/notebooks/cross_contour`

**Comment by adele157** [comment]
Nice one Claire! That’s a pretty dramatic drop in the DSW export,
consistent with the increase in bottom age in the abyss.

Is the heat transport relative to 0degC or the freezing point temperature?

**Comment by claireyung** [comment]
<img width="622" alt="Screen Shot 2022-10-29 at 12 36 17 am" src="https://user-images.githubusercontent.com/61528379/198616067-03b54b67-c9e8-414a-95b7-8eed85fa4112.png">

Heat transport is now relative to -5 degrees C -- agrees with Morrison et al. (2020) supp. material? (Would be better to have the actual minimum freezing point instead of something arbitrary though)

**Comment by claireyung** [comment]
<img width="656" alt="Screenshot 2022-11-23 at 9 36 16 am" src="https://user-images.githubusercontent.com/61528379/203435434-33aee97d-84ba-4d78-8716-2b7e00c20901.png">
Updated Gade line formulation overturning has a very similar weakening in overturning as the heat balance formulation

**Comment by adele157** [comment]
This last plot is great! Nice to see we still have overturning with the Gade line formulation - the impact of the extra freshening at depth on density is being compensated by cooling relative to the GPC13 simulation.

**Comment by claireyung** [comment]
Updated 10 year results for Gade line basal melt experiment showing reduction in overturning of ~2Sv that stabilises after 5 ish years

<img width="884" alt="Screenshot 2022-12-16 at 11 39 38 am" src="https://user-images.githubusercontent.com/61528379/207995870-feffc09b-9b9e-4e9a-8481-f628746b9d59.png">

**Comment by adele157** [comment]
Nice! I'm excited to see how this changes again once we implement the
iceberg runoff. I predict it will increase again.

**Comment by pedrocol** [comment]
Hi Claire,

Is the one in the plot GPC013 or GPC015? The gade line one is 15.

Cheers,

Pedro.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by claireyung** [comment]
It's GPC015!

The GPC013 (for 5 years) is up in a higher comment and has greater reduction of overturning.

**Comment by claireyung** [comment]
Interestingly, with another 10 years of data, the overturning seems to grow slightly again (dotted lines are 10-20 years) to have a new overturning maximum at a lighter density:
<img width="1049" alt="Screenshot 2023-02-24 at 4 39 46 pm" src="https://user-images.githubusercontent.com/61528379/221100935-1e797aeb-3526-421e-a50a-c0d51213f9c9.png">

**Comment by adele157** [comment]
Interesting. Maybe some time series would be handy to see the rate of adjustment. Could do a few versions:
* time series of transport at fixed density (perhaps the control peak density value would work)
* Time series of peak transformation rate
* Time series of density of peak transformation

**Comment by claireyung** [comment]
Time series of transport at fixed density:
![image](https://user-images.githubusercontent.com/61528379/223867157-c95785ce-77b2-44f8-b467-bed590fdc5c4.png)

Time series of peak transport:
![image](https://user-images.githubusercontent.com/61528379/223866465-0e8cfda8-9b9b-4761-a0e6-3f99a70624de.png)

Time series of density of peak transport:
![image](https://user-images.githubusercontent.com/61528379/223864866-ce9d3efd-d5a5-4de1-956e-81f821e67e2e.png)

**Comment by claireyung** [comment]
**Transport Plots by DSW sector**

Main transport reduction from Ross/Adelie, Weddell has lightening of peak transport. Note Weddell sector includes the peninsula.

Note no iceberg run plots yet but will compute soon :)

![image](https://user-images.githubusercontent.com/61528379/223910370-8c739f94-9e10-45e5-ae44-995892739051.png)

**Comment by claireyung** [comment]
**Iceberg (GPC018) results - even stronger decrease in DSW export than the basal run**

![image](https://user-images.githubusercontent.com/61528379/225808298-7a1a7d83-3d5d-4983-b607-3f1910600104.png)
![image](https://user-images.githubusercontent.com/61528379/225808379-1f02b304-f1ac-49a9-ad81-3c4068bdb1a5.png)
![image](https://user-images.githubusercontent.com/61528379/225808400-b014f5f0-e891-4aaf-a793-08a574790294.png)
**Cumulative cross-contour transport in density classes:**
![image](https://user-images.githubusercontent.com/61528379/225819986-0af659e0-fb14-40fb-a9eb-dabb33874961.png)

Change in DSW export locations for iceberg run.  Also suggests strong lightening of Prydz export as no longer appears in DSW density class? Confirmed by regional integrals:
![image](https://user-images.githubusercontent.com/61528379/225824256-f65bec41-5e71-4a9f-be26-738a5289a57c.png)

**Comment by adele157** [comment]
Interesting! We expected it to increase again. Any ideas why DSW decreases further in the iceberg experiment?

**Comment by PaulSpence** [comment]
So icebergs decrease DSW and the MOC. Maybe we need to look at the salt balance on the shelf - like in the easterlies project.

**Comment by claireyung** [comment]
Adele pointed out that in the density class sigma_1 > 32.56, DSW export is bigger in the iceberg run than in the basal-only run, which may be the relevant DSW for export into deeper ocean/AABW/MOC (see figures above with black, pink and blue lines showing transport across isobath contour cumulatively integrated)

So the southward export is slightly bigger in the basal-only run, but it's in a lighter density class so may not get into the abyss. @PaulSpence how does the iceberg MOC look at year 15?

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new cross-slope transport issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/65.
