### ISSUE TITLE
Overturning / ice pump circulation 

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#3]
Suggestion from Matt in a different issue:

"Some zoomed in overturning circulation plots over the shelf, to see how the MW at depth is triggering an inverse circulation response there cf control."

How do we best show this? We could try looking at regular density / latitude overturning, but it may be hard to distinguish ice pump circulation from changes in the abyssal overturning. But worth a look anyway.

We could also plot the cross-1000m isobath transports in different density classes as a function of isobath distance. That could be informative to see if there is more cross-slope exchange in the Amundsen region for example.

**Comment by PaulSpence** [comment]
Just the basic MOC so far:
![Screenshot 2023-03-15 at 4 54 34 pm](https://user-images.githubusercontent.com/6644956/225219687-30b701ba-da24-4417-974a-77e2bbce45bc.png)

I'll try trickier things next :)

**Comment by adele157** [comment]
Looks like not too much change here? Interesting because there were [fairly large changes in dense water export across the 1000m isobath](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/28#issuecomment-1442837971) .

@claireyung has calculated the cross slope transports in density classes. Claire, do you reckon you could put the path to those files here and we could plot them for different regions to try to see how cross slope transports change in regions where we might expect to see some ice pump circulation (Amundsen perhaps?).

**Comment by claireyung** [comment]
Output of cross-1000m isobath transport is in `/g/data/x77/cy8964/Post_Process/access-om2/accessom2-GPC0XX/Antarctic_cross_slope/` where `XX`=`18` or `15`, in monthly averages. Control is from Adele, `'/g/data/v45/akm157/model_data/access-om2/01deg_jra55v13_ryf9091_rerun_for_easterlies/Antarctic_cross_slope/`

I haven't quite finished the iceberg run analyses (18) yet though.

**Comment by adele157** [comment]
Closing as this uses data from old simulations. New issue is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/67).
