### ISSUE TITLE
Temperature / salinity maps and time series

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#31]
Plots maps of bottom, depth integrated and surface change in temperature and salinity. Also time series of volume integrated quantities and perhaps for selected regions/depths of interest.

Issue on this using old simulations is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/5).

**Comment by adele157** [comment]
The Gade line formulation has less freshening overall on the shelf compared to the heat balance formulation:

<img width="857" alt="Screen Shot 2022-11-23 at 10 24 14 am" src="https://user-images.githubusercontent.com/8506963/203441135-471d89bd-d1cb-40e9-a3a7-2836eaa0bf78.png">

The input of freshwater (basal melt) is the same in both cases. Perhaps this is due to a sea ice feedback? We get [more sea ice](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1324364786) in the Gade line formulation, which will result in more brine rejection over the shelf. Maybe this extra salt input from the sea ice formation is enough to counteract some of the freshening at depth we see from the basal melt?

**Comment by adele157** [comment]
There is an overall cooling on the shelf in the Gade line formulation simulation compared to the RYF. This makes sense, because we're taking out a lot more heat from the ocean when we put in the basal melt, compared with the heat balance formulation.
<img width="620" alt="Screen Shot 2022-11-23 at 10 38 21 am" src="https://user-images.githubusercontent.com/8506963/203442788-4277f50b-10b5-4bc1-ab18-fd0875a08b62.png">

**Comment by adele157** [comment]
And a couple of regional time series of bottom temperature.

In the Amundsen (-115W to -100W):
<img width="500" alt="Screen Shot 2022-11-23 at 11 21 30 am" src="https://user-images.githubusercontent.com/8506963/203451265-e4fc4b7a-bdb7-4434-b4b0-00f52e577781.png">

And in the East Ross (-175W to -140W):
<img width="500" alt="Screen Shot 2022-11-23 at 12 06 34 pm" src="https://user-images.githubusercontent.com/8506963/203451321-fa59b718-548b-4ed5-a0c9-f65c94e67ba8.png">

**Comment by adele157** [comment]
I updated the time series above with the longer simulation. Here are maps of bottom temperature change compared to the RYF control over years 4-8 (left) and years 14-16 (right). Clear patterns of a weakening abyssal cell (cooling on the shelf downstream from DSW formation regions and warming in the abyss). The initial cooling in the Amundsen weakens over time (also seen in time series above).

<img width="1030" alt="Screen Shot 2023-01-13 at 4 30 07 pm" src="https://user-images.githubusercontent.com/8506963/212244737-7fa1523d-4bdf-44c6-aa5a-08e6ad5b7f90.png">

**Comment by adele157** [comment]
Here are maps of SST change in the basal run for two different time periods:

<img width="800" alt="Screen Shot 2023-02-23 at 3 50 20 pm" src="https://user-images.githubusercontent.com/8506963/220823768-4b04bf57-6ef0-4b5e-a207-b41d7854e353.png">

Cooling pretty much everywhere, which aligns with the [sea ice thickness increase](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1441185435).

**Comment by hrsdawson** [comment]
Surface temperature(top row) and salinity (bottom row) changes between the Basal melt run and Control (left column) Basal + Icebergs minus Control (middle column) and Basal+Icebergs minus Basal (right column). Adding the iceberg distribution causes a freshening along the coast over much of East Antarctica, along with a strong freshening at the eastern Antarctic Peninsula and northern Weddell Gyre region. 

<img width="1320" alt="Screen Shot 2023-03-09 at 10 46 45 am" src="https://user-images.githubusercontent.com/62230733/223878716-01eef146-6cfa-469e-9ce4-444052486049.png">

**Comment by hrsdawson** [comment]
Here's the same temperature and salinity comparison but for the 300-1000m depth. Adding meltwater at depth cools the Amundsen Sea and far eastern Weddell Sea in this depth range while also freshening the entire shelf, except the Bellingshausen Sea. Adding in the ice berg distribution warms the shelf in East Antarctica and parts of the Amundsen Sea and also increases salinity along most of the shelf except the eastern Weddell Sea and downstream of the Prydz Bay region. 

<img width="1335" alt="Screen Shot 2023-03-09 at 11 02 29 am" src="https://user-images.githubusercontent.com/62230733/223880768-9bc9733d-027c-4a29-b746-96a49acc1512.png">

**Comment by hrsdawson** [comment]
Bottom temperature and salinity changes. Freshening on the bottom from the basal melt simulation. Salinification on the bottom (except downstream of Prydz Bay and eastern Weddell Sea) from the iceberg distribution. Adding the icebergs also causes warming of bottom shelf water along East Antarctica.  

These last 3 plots are from the 7th year of simulation. 

<img width="1330" alt="Screen Shot 2023-03-09 at 11 12 48 am" src="https://user-images.githubusercontent.com/62230733/223881873-d055341f-c6fe-433d-89cb-e69514ad7277.png">

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new temp/salt analysis issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/63.
