### ISSUE TITLE
Sea ice changes

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#33]
- Time series of sea ice extent and volume.
- Maps of concentration and thickness change.
- Comparison with obs.

Previous issue using old simulations is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/9).

**Comment by adele157** [comment]
There are some notes on observational sea ice products to compare against in these comments:
- https://github.com/pedrocol/basal_mom5-collaborative-project/issues/18#issuecomment-1225209914
- https://github.com/pedrocol/basal_mom5-collaborative-project/issues/18#issuecomment-1226648330

**Comment by adele157** [comment]
Posting Pedro's sea ice plot (from year 3) here, so I can link to it elsewhere:

<img width="675" alt="Screen Shot 2022-11-23 at 10 28 42 am" src="https://user-images.githubusercontent.com/8506963/203441605-7aab86b8-ae7c-4e12-95bb-322dd78af646.png">

Gade line formulation looks better here than heat balance formulation.

**Comment by pedrocol** [comment]
Posting time series of sea ice volume

![Screenshot from 2022-11-23 11-04-35](https://user-images.githubusercontent.com/23285319/203445441-cc6160a7-7c63-4ae2-9b84-1a3b3468e11e.png)

**Comment by pedrocol** [comment]
Posting maps of sea-ice thickness of the 3rd year mean
![Screenshot from 2022-11-23 11-06-48](https://user-images.githubusercontent.com/23285319/203445662-9510b9f3-7c61-43e6-8ae4-5c342b58fdcd.png)

**Comment by aekiss** [comment]
Just a note: the "sea ice area" plot [above](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1324364786) is actually more like the extent, but using a threshold of zero thickness (rather than the usual 15% SIC).

This should be re-plotted as area (sum of SIC times cell area).

**Comment by aekiss** [comment]
Here's the average sea ice concentration difference for the 3 cases. The differences are pretty small.
![image](https://user-images.githubusercontent.com/31054815/203467924-e16ce54e-d22b-4ab7-82c7-92d3c93f55f4.png)

Consequently the SIC bias is nearly identical in the 3 cases (relative to 1 May 1990 - 30 April 1991 obs, to match RYF):
![image](https://user-images.githubusercontent.com/31054815/203468187-c3589428-d8e5-447c-a39c-084bf853a551.png)

**Comment by aekiss** [comment]
Here are the February thickness and SIC differences, and SIC bias
![image](https://user-images.githubusercontent.com/31054815/203469049-9157c73f-c386-4fd1-b2ac-56661aaa1a43.png)
![image](https://user-images.githubusercontent.com/31054815/203469112-85d124af-a405-4e9c-8b23-0af91a7fb6a6.png)
![image](https://user-images.githubusercontent.com/31054815/203469128-39ab9a9e-eafa-489a-9839-f3b2d95518fa.png)

**Comment by aekiss** [comment]
This doesn't seem consistent with a significant improvement in sea ice with Gade suggested by the plot [above](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1324364786).

**Comment by aekiss** [comment]
Here's the extent (model monthly climatology of area with SIC>15%) in comparison with obs over the RYF period.

Consistent with my plots above, Gade is not a significant improvement (contradicting the conclusion from the plot [above](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1324364786), but that's because [it isn't showing the model sea ice extent](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1324450519)).

![image](https://user-images.githubusercontent.com/31054815/203897691-503d2cb3-7a98-441d-9870-b4d2c7107104.png)

**Comment by adele157** [comment]
Bugger! Oh well, the Gade line formulation is still better on other
metrics. Do we have any chance of validating the sea ice thickness
that does show a difference?

**Comment by aekiss** [comment]
We could compare to GIOMAS thickness, but that's from a model that only assimilates SIC (IIRC)

**Comment by PaulSpence** [comment]
Some updated figs of the sea ice:

Sea ice thickness anoms (mean from years 15-20):
![Screen Shot 2023-02-23 at 2 50 43 pm](https://user-images.githubusercontent.com/6644956/220817640-1aea66f1-bd22-42e3-a30d-2b9713e97d2a.png)

**Comment by PaulSpence** [comment]
Annual mean Sea ice conc. anoms (mean from years 15-20):
![Screen Shot 2023-02-23 at 2 53 28 pm](https://user-images.githubusercontent.com/6644956/220817866-7fd928d0-bb66-4a8f-9eeb-f16f3bf5963e.png)

Feb. mean Sea ice conc. anoms (mean from years 15-20):
![Screen Shot 2023-02-23 at 2 53 28 pm](https://user-images.githubusercontent.com/6644956/220817911-67e96d2b-d4b8-421b-953c-fc3cfe714d9a.png)

**Comment by PaulSpence** [comment]
Monthly Southern Ocean Sea Ice Volume:
![Screen Shot 2023-02-23 at 2 54 28 pm](https://user-images.githubusercontent.com/6644956/220817986-f1ec7ecf-c368-413c-adb5-9c8d87a7c51c.png)

Annual mean Southern Ocean Sea Ice Volume:
![Screen Shot 2023-02-23 at 2 54 34 pm](https://user-images.githubusercontent.com/6644956/220818016-5cdd61d0-e304-43d9-b593-3c4828911bae.png)

**Comment by adele157** [comment]
Nice one Paul. Can we get some understanding/explanation going on here also? 

e.g. The sea ice volume and thickness increases because...

**Comment by PaulSpence** [comment]
Pretty sure the sea ice patterns generally match the ocean temp, i.e. colder on the shelf:
https://github.com/pedrocol/basal_mom5-collaborative-project/issues/37#issuecomment-1324337095

Can dig deeper later.

**Comment by aekiss** [comment]
Thanks Paul - that's quite a big impact.

You might want to check the [SIC anomaly plots](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33#issuecomment-1441186573) - they look the same.

**Comment by hrsdawson** [comment]
Monthly timeseries of sea ice volume across the simulations. Both the Basal and Basal + Iceberg runs cause an increase in the sea ice volume compared to the control.  It would be good to look at a timeseries of sea ice extent compared with observations. Does this increased sea ice volume translate to a greater summer sea ice extent, which is currently too small in the control run compared to observations?

<img width="1341" alt="Screen Shot 2023-03-09 at 11 00 58 am" src="https://user-images.githubusercontent.com/62230733/223880516-e91fc6d1-ebfd-4945-a242-46f820fb6259.png">

**Comment by PaulSpence** [comment]
Modest improvement in summer SI extent relative to obs with icebergs:
![Screen Shot 2023-03-09 at 1 33 11 pm](https://user-images.githubusercontent.com/6644956/223901079-58d30b69-8768-4067-97d4-df39664d640d.png)

**Comment by PaulSpence** [comment]
![Screen Shot 2023-03-09 at 1 37 29 pm](https://user-images.githubusercontent.com/6644956/223901519-a981adf2-4d30-4974-9f50-488fe7dc02b4.png)

**Comment by PaulSpence** [comment]
![Screen Shot 2023-03-09 at 1 39 28 pm](https://user-images.githubusercontent.com/6644956/223901844-5769cd2b-5213-4b0d-b532-987ee1300159.png)

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new sea ice issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/64.
