### ISSUE TITLE
Change in runoff heat flux

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#35]
The basal melt enters the ocean with a [different temperature](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/24) to the surface runoff in the control simulation. Quantify how much this heat flux changes. Also, how large an effect is this in the context of the whole shelf heat budget (i.e. considering all surface/frazil heat fluxes and cross-slope advective fluxes)?

Previous issue using old simulations [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/6).

**Comment by pedrocol** [comment]
Time series of Control and Basal_Heat_Balance
![Screenshot from 2022-11-23 11-47-24](https://user-images.githubusercontent.com/23285319/203449935-912b9685-a0e5-42a7-9023-f2587aaac81e.png)

Time series of Control and Basal_Gade, note the change in the scale
![Screenshot from 2022-11-23 11-54-03](https://user-images.githubusercontent.com/23285319/203449939-85ee0ab5-0b64-45c7-9a48-bbd084b234ce.png)

**Comment by adele157** [comment]
Closing this issue, as it's duplicated by [this other issue](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/2).
