### ISSUE TITLE
Temp / salt comparison with observations

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#37]
Compare against the [Pathenet et al. 2021 climatology](https://zenodo.org/record/4071906#.YwWmKJNBxqs) for upper ocean temp/salt, and against Schmidtko et al. 2014 for bottom shelf temperature.

Previous issue using old simulations is [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/18).

**Comment by mmr0** [comment]
Amery/Prydz bay
![Screen Shot 2022-11-17 at 10 45 56 am](https://user-images.githubusercontent.com/17136023/202319283-28cf9109-09be-4eb9-a39e-8e6bfe8cb619.png)

doi:10.1002/2015JC010697

**Comment by mmr0** [comment]
+ just found this, which looks at many sectors:
![Screen Shot 2022-11-17 at 10 59 25 am](https://user-images.githubusercontent.com/17136023/202320971-bb637a8a-e754-4957-b4d3-8bc898463e1f.png)

 https://doi.org/10.1029/2018JC014907

**Comment by pedrocol** [comment]
![Screenshot from 2022-11-23 09-47-10](https://user-images.githubusercontent.com/23285319/203436888-31609115-4162-4251-815d-b9b0d1928e59.png)

**Comment by adele157** [comment]
Bottom temperature comparison with Schmidtko (in year 3):

<img width="1211" alt="Screen Shot 2022-11-23 at 12 05 55 pm" src="https://user-images.githubusercontent.com/8506963/203451399-4f282d02-d736-4cef-bad4-25a32b4e5e3f.png">

Surprisingly similar... Gade line formulation is better in the East Ross and both basal simulations are perhaps a bit better in the Amundsen.

**Comment by hrsdawson** [comment]
Here's some updated plots of T-S from the control and Gade simulation against Pauthenet observations in the upper ocean (10-100m):

![Screenshot from 2023-02-09 10-44-26](https://user-images.githubusercontent.com/62230733/217679262-e359af99-c105-45bb-95af-806dac6eed52.png)


and 200-380m depth:

![Screenshot from 2023-02-09 11-12-12](https://user-images.githubusercontent.com/62230733/217680978-c0e0f62e-6465-44a0-95d7-e8392b9059d8.png)



Compared to the control, the Gade simulation has reduced salinity biases in the Ross Sea and the Weddell Sea surface region, and reversed salinity biases in the Weddell Sea from 200-380m. Temperature differences between the control and the Gade simulation are less clear. There's reduced temperature bias in the Amundsen Sea (at depth) at the start of the Gade simulation, but this seems to increase (warm) over time.

**Comment by hrsdawson** [comment]
> Hard to tell much difference between GPC013 and GPC15. I guess that means that the Gade line formulation is not worse. GPC15 looks better in the Ross Sea. Maybe a transect of these biases through the Amundsen Sea would be useful? The bias in the Amundsen is huge and hard to tell the difference with the saturated colour scale there.

Here's some transects through the Amundsen Sea. Only small differences at 104W. Larger differences at 110W (reduced subsurface biases in Gade simulation compared to control), however I'm not sure how much I trust the observations in this region given the artefacts in the obs at ~71S. 


<img src="https://user-images.githubusercontent.com/62230733/217708215-fa22c877-ce0c-4a8b-b614-64f6ce6ab88b.png" width=50%><img src="https://user-images.githubusercontent.com/62230733/217708226-ea9e5b98-cb38-4ec9-ae5d-1d758812d650.png" width=50%>

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new temp/salt analysis issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/63.
