### ISSUE TITLE
T/S diagrams

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#4]
Suggestion from Ben in another issue:

"How about some theta-S diagrams as well. I'm still interested to see these."

I'm guessing we want these for individual regions. Do we want to try also zooming in on regions close to the coast where the meltwater is being released?

**Comment by bkgf** [comment]
Absolutely -or even coloured by proximity...

**Comment by hrsdawson** [comment]
Some basic T-S diagrams in[ this](https://github.com/pedrocol/basal_mom5-collaborative-project/blob/main/notebooks/TS_diag/TS_diagrams.ipynb) notebook. Designed so you can plot for any region (e.g. much closer to coast near high meltwater) using `read_and_convert_TS(lat_slice, lon_slice, start_time, end_time)`. Currently only coloured by depth or latitude.

**Comment by adele157** [comment]
Nice! Can you paste some example figures in this issue @hrsdawson? Then it's easier for people to comment on.

**Comment by hrsdawson** [comment]
Yep, I've just plotted some T-S examples from these three regions so far. 
![Screenshot from 2022-08-25 06-12-08](https://user-images.githubusercontent.com/62230733/186514590-10dc02e2-2ae4-4ca1-8846-0826a0c89c25.png)

This is the Amundsen Sea shelf section coloured by latitude (can expand to include the other 2 simulations):
![Screenshot from 2022-08-25 06-12-23](https://user-images.githubusercontent.com/62230733/186514613-7a251d57-6947-4291-ab30-89366b8cd0b9.png)

And this is the East Antarctic shelf region:
![Screenshot from 2022-08-25 06-12-59](https://user-images.githubusercontent.com/62230733/186514644-b45ae585-2088-4f33-9019-ecf6b05b95f9.png)

**Comment by adele157** [comment]
Summarising some of the suggestions / discussion from today's meeting on these plots:

1. Can we have a T/S diagram for the southern Weddell Sea shelf too? It may shed some light on the massive sea ice changes we're seeing there.

2. There were suggestions to weight the points by the volume of the grid cells. Either a histogram where colour shows volume, as in the COSIMA recipes example. Or maybe a better approach is to first regrid the data onto an evenly spaced vertical grid (e.g. with 50 m spacing), so that the surface points don't dominate the figure. That way we can still colour by depth which is useful.

3. The Amundsen Sea T/S plot shows a massive change in water mass properties at the high salinity range (S>34). Can we find out more about what is going on here? Maybe spatially locate where it is and do some T/S plots for smaller regions to see exactly which water masses are mixing more and why. Some paper from Ben with T/S obs from the Amundsen that might be useful to see if the simulation is getting more or less realistic in this region:
https://www.nature.com/articles/s41467-022-28751-5
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2019JC015133

4. It would be great to compare these with obs more if possible to know if particularly the denser side of these distributions are getting any more realistic in the pertubation.

**Comment by hrsdawson** [comment]
Thanks for the recap @adele157, will get onto these suggestions this week.

**Comment by aekiss** [comment]
re. 2, regridding will reduce the sampling bias but won't fix the problem of overlapping scatter points, so it will still draw attention towards outliers and underemphasise the regions is T/S space where the bulk of the fluid lies. This problem is eliminated by a 2d histogram, but it's also nice to be able to colour by depth. Using very small and/or translucent scatter points would help with the overlap issue.

**Comment by hrsdawson** [comment]
Here's the T-S figures from the **Amundsen Sea** region, interpolated onto 50 m vertical grid and coloured by depth using a small alpha. The T-S changes are coming from what I've called the 'inner shelf' regions in the reference figure ('west' is roughly in front of the Crosson Ice Shelf, central - Thwaites Glacier, and east - Pine Island). Small contribution from the central shelf and no contribution from the outer shelf. Should I zoom in further on any particular region?

![image](https://user-images.githubusercontent.com/62230733/188771966-5135dd51-ecd2-444e-837b-1913b0e66b2f.png)
![image](https://user-images.githubusercontent.com/62230733/188771989-4b9ad212-c5a4-4879-b7ee-656d2c1a6798.png)
![image](https://user-images.githubusercontent.com/62230733/188772017-361cc55e-4aa7-4ec4-bf3d-fde1e2666393.png)
![image](https://user-images.githubusercontent.com/62230733/188772041-2723ef0d-8463-4c8c-be8b-766a682fc3f0.png)
![image](https://user-images.githubusercontent.com/62230733/188772060-05654a2f-7e8f-4bd9-9b8b-82ac0aac39db.png)
![image](https://user-images.githubusercontent.com/62230733/188772082-5146e61a-900e-4457-acbb-0d16d20e4574.png)


Here's a T-S plot for the broad southern **Weddell Sea** shelf - changes are not as obvious as for the Amundsen Sea except we're loosing some of the fresher surface waters and gaining some dense waters. 
![image](https://user-images.githubusercontent.com/62230733/188779793-fb743b36-cc28-4b6d-86a2-8ccab43e0819.png)

![image](https://user-images.githubusercontent.com/62230733/188779681-3ff20bb3-1c71-4d43-b22b-a30eb7b1d960.png)

**Regarding observations:** Across how large of a region should this be done? Do you recommend selecting closest vertical column to each obs, using a broader region - maybe 0.1 deg in each direction, or across the whole ice shelf front (in the case of the nature comms paper)?

**Comment by hrsdawson** [comment]
(FYI at the moment I'm selecting closest vertical columns - will post figure once it's done. If it looks no good, I'll expand the region).

**Comment by pedrocol** [comment]
Thanks for the plots Hannah! In case choosing the different regions becomes an issue, for the Hovmoller plots (notebook [TSrho_anom_hovmo](https://github.com/pedrocol/basal_mom5-collaborative-project/tree/main/notebooks/TSrho_anom_hovmo)) I constrain only a portion of the shelf

![Screenshot from 2022-09-07 00-24-41](https://user-images.githubusercontent.com/23285319/188787343-d9f5ad7c-c6d6-43a9-ba6d-9dbf3058ba00.png)

**Comment by hrsdawson** [comment]
Thanks @pedrocol. Here's some comparisons with Yang et al. (2022). I've selected the closest vertical column from the model to each of the moorings and interpolated onto the instrument depths. Something isn't quite right though - the density contours are offset from those in the obs figure but I haven't worked out why yet. Note the extended x-axis for the model data. 

![image](https://user-images.githubusercontent.com/62230733/188799355-b0ec5d28-8f89-4d34-81dd-20aa210bb2d0.png)
![image](https://user-images.githubusercontent.com/62230733/188799389-19ef8832-f822-4adb-855e-c69fbdcf94b1.png)

**Comment by hrsdawson** [comment]
This is where the main T-S changes in the Amundsen Sea are coming from (i.e. the region in red on the right T-S plot). The depth is coloured such that the deepest point at a particular lat-lon is shaded. 

<img width="1214" alt="Screen Shot 2022-09-22 at 5 47 09 pm" src="https://user-images.githubusercontent.com/62230733/191688570-cefac062-5061-4603-958e-f2683049815e.png">
<img width="1003" alt="Screen Shot 2022-09-22 at 5 56 36 pm" src="https://user-images.githubusercontent.com/62230733/191690464-1c3ac4ab-e3e0-4dbe-93c4-6dff12f007d1.png">

**Comment by adele157** [comment]
Closing this issue because it uses the old simulations. See new T/S diagrams issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/30).
