### ISSUE TITLE
Check if we can close the heat budget with the existing diagnostics

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#53]
It sounds like there might be issues with the heat flux coming from runoff and the net surface heat flux diagnostics. Can we close the heat budget if we ignore the contribution of the basal and iceberg fluxes to these diagnostics?

**Comment by adele157** [comment]
I attempted to close the globally integrated heat budget (i.e. balancing surface + frazil + basal heat fluxes with the heat content change). 

For the control, this closes extremely well:
heat content change over 5 years = -31.76366 x 10^20 J
heat budget residual over 5 years = 0.00002 x 10^20 J

For the basal only run (accessom2-GPC015), I can not close the heat budget:
heat content change over 1 year = -122.7174 x 10^20 J
heat budget residual (after subtracting all heat fluxes including temp_basalmix) over 1 year = -109.5963 x 10^20 J

More details in [this notebook](https://github.com/pedrocol/basal_mom5-collaborative-project/blob/main/notebooks/heat_budget/close_heat_budget.ipynb).

@pedrocol any idea why this is not closing?

**Comment by pedrocol** [comment]
I'll take a look, I just have one comment so far, sfc_hflux_from_runoff is the variable that we discussed yesterday, and it is a heat flux relative to 0deg and not a heat flux to the ocean, I'm not sure if we should use that in this calculation

**Comment by adele157** [comment]
But we still need to include sfc_hflux_from_runoff for the calving (at the coast in accessom2-GPC015) and the rest of the globe. The basal input doesn't contribute at all to sfc_hflux_from_runoff does it?

**Comment by pedrocol** [comment]
There was a mistake in the restart folder, it should have been 1002 instead of 999, it now closes
Net heat content change over this period = -13.121108775757548 x 10^20 J
Net surface heat input plus basal over this period = -13.121118571674007 x 10^20 J
Heat budget residual = 9.79591646019584e-06 x 10^20 J

**Comment by adele157** [comment]
Ah excellent! Yes, I had assumed 3 month run chunks, oops.

So I think we're all good to proceed with the iceberg run then? Is the plan
still to rewrite the code to deal with the iceberg flux the same way you
dealt with the basal flux, and then to restart the iceberg run from year
2150 again?

**Comment by pedrocol** [comment]
Yes! I should normally have the new code ready and completed two years for the next meeting

**Comment by adele157** [comment]
Sounds good. Let me know when you start running and we can do the heat
budget check again on the new iceberg heat flux diagnostic also.

**Comment by adele157** [comment]
Budgets close!
