### ISSUE TITLE
GPC015 output1099 daily files not collated 

### ISSUE THREAD

**Issue by claireyung** [pedrocol/basal_mom5-collaborative-project#56]
Hi @Pedro, I was just trying to calculate overturning for the second 10 years of the Gade line basal melt experiment and got an error for the months that are in output1099. It appears that the daily files are not collated in `/g/data/ik11/outputs/access-om2-01/basal_melt_outputs/accessom2-GPC015/accessom2-GPC015/output1099/ocean/`. Would you be able to collate these files? (Or tell me how to and I can try!)
Thanks!

**Comment by aekiss** [comment]
Looks like @pedrocol will need to do it due to permissions. Switch to the control directory and try this:
```
payu collate -d /g/data/ik11/outputs/access-om2-01/basal_melt_outputs/accessom2-GPC015/accessom2-GPC015/output1099/ocean
```

**Comment by pedrocol** [comment]
Done, thanks for the instructions Andrew!
