### ISSUE TITLE
Runoff heat flux

### ISSUE THREAD

**Issue by adele157** [pedrocol/basal_mom5-collaborative-project#6]
How much does the heat flux into the ocean from the runoff change? Plot integrated over the shelf as a function of longitude perhaps.

**Comment by pedrocol** [comment]
This is the plot as a function of longitude in a 5 years time mean
![Screenshot from 2022-08-16 21-41-42](https://user-images.githubusercontent.com/23285319/185009031-f8fcdef3-9e8c-45cd-83af-98f5ea1b16d8.png)
In more detail between -160 and -80
![Screenshot from 2022-08-16 21-41-51](https://user-images.githubusercontent.com/23285319/185009035-6ff66978-08d7-4117-9d04-eb4d5f2952e1.png)
 The highest difference is found between -110 and -100, which corresponds to the Amundsen sea

**Comment by adele157** [comment]
Closing, as this uses old simulations. New issue [here](https://github.com/pedrocol/basal_mom5-collaborative-project/issues/35).
