### ISSUE TITLE
New parameterization crash

### ISSUE THREAD

**Issue by pedrocol** [pedrocol/basal_mom5-collaborative-project#61]
There is a recurrent crash in the runs using the new version of the parameterization. It occurs mainly in October in the first few years, but then also happens in May/June/July/August. I had to reduce the time step to 100s (normally 450s / 540s), but during the 5th year, it crashes even using such a small time step.

It seems to me that is not CICE who is crashing (no prints in ice.log.task_*). The code line reference in the error (see below), is the following (no changes were performed in that part of the MOM5):

rhodz_taup1(i,j)= rhodz_taup1(i,j)+ Grd%tmask(i,j,k)*rho0r*Thickness%rho_dzt(i,j,k,taup1)*Dens%rho(i,j,k,taup1)

Maybe adding some extra viscosity/diffusivity would fix it?

------

Here is part of the error file:

Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2d575000) 

backtrace (tid:2188466)

 0 0x0000000000012cf0 __funlockfile()  :0
 1 0x000000000065d12d ocean_density_mod_mp_compute_density_diagnostics_()  /home/552/pc5520//access-om2/src/mom/src/mom5/ocean_core/ocean_density.F90:3069
 2 0x0000000000646ae2 ocean_density_mod_mp_update_ocean_density_()  /home/552/pc5520//access-om2/src/mom/src/mom5/ocean_core/ocean_density.F90:2271
 3 0x0000000000431150 ocean_model_mod_mp_update_ocean_model_()  /home/552/pc5520//access-om2/src/mom/src/mom5/ocean_core/ocean_model.F90:1959
 4 0x0000000000422888 MAIN__()  /home/552/pc5520//access-om2/src/mom/src/accessom_coupler/ocean_solo.F90:464
 5 0x000000000040f4a2 main()  ???:0
 6 0x000000000003ad85 __libc_start_main()  ???:0
 7 0x000000000040f3ae _start()  ???:0

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fms_ACCESS-OM_97e  0000000001B82A73  Unknown               Unknown  Unknown
libpthread-2.28.s  000014DA800B6CF0  Unknown               Unknown  Unknown
fms_ACCESS-OM_97e  000000000065D12D  ocean_density_mod        3069  ocean_density.F90
fms_ACCESS-OM_97e  0000000000646AE2  ocean_density_mod        2271  ocean_density.F90
fms_ACCESS-OM_97e  0000000000431150  ocean_model_mod_m        1959  ocean_model.F90
fms_ACCESS-OM_97e  0000000000422888  MAIN__                    464  ocean_solo.F90
fms_ACCESS-OM_97e  000000000040F4A2  Unknown               Unknown  Unknown
libc-2.28.so       000014DA7FD18D85  __libc_start_main     Unknown  Unknown
fms_ACCESS-OM_97e  000000000040F3AE  Unknown               Unknown  Unknown

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
cice_auscom_3600x  000000000089E584  Unknown               Unknown  Unknown
libpthread-2.28.s  000014C789745CF0  Unknown               Unknown  Unknown
libopen-pal.so.40  000014C788A4A6D5  Unknown               Unknown  Unknown
libopen-pal.so.40  000014C7889E85C4  Unknown               Unknown  Unknown
libopen-pal.so.40  000014C7889E874B  opal_progress         Unknown  Unknown
libmpi.so.40.20.1  000014C78ADA25D5  ompi_request_defa     Unknown  Unknown
libmpi.so.40.20.1  000014C78ADE623F  PMPI_Waitall          Unknown  Unknown
libmpi_mpifh.so    000014C789D2898D  Unknown               Unknown  Unknown
cice_auscom_3600x  00000000007D02F0  Unknown               Unknown  Unknown
cice_auscom_3600x  00000000007CF196  Unknown               Unknown  Unknown
cice_auscom_3600x  00000000007526BC  mod_oasis_advance        1130  mod_oasis_advance.F90
cice_auscom_3600x  00000000006C0608  mod_oasis_getput_         659  mod_oasis_getput_interface.F90
cice_auscom_3600x  000000000043425A  cpl_interface_mp_         553  cpl_interface.f90
cice_auscom_3600x  0000000000411903  cice_runmod_mp_ci         240  CICE_RunMod.f90
cice_auscom_3600x  000000000040DA9C  MAIN__                     70  CICE.f90
cice_auscom_3600x  000000000040DA22  Unknown               Unknown  Unknown
libc-2.28.so       000014C7891A3D85  __libc_start_main     Unknown  Unknown
cice_auscom_3600x  000000000040D92E  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)"

**Comment by StephenGriffies** [comment]
Typically, when confronted with these sorts of errors, it is necessary to look at fields to see if there is any clue to what is happening.  To do so requires starting the model just before the crash and enabling selective diagnostics each time step.  Otherwise, you are working  in the dark.  It is tedious but the only way to garner more information.  

One guess is that there is a negative salinity and the equation of state is going haywire, thus producing NaN in Dens%rho(i,j,k,taup1).

Some EOS codes have hack by using abs(saln) to avoid taking the sqrt of a negative salinity.  I am unsure if that hack is coded into the TEOS10 version in MOM5 used in your simulations.

**Comment by aekiss** [comment]
Wouldn't negative salinity produce a floating point error rather than a segmentation fault?

**Comment by pedrocol** [comment]
I checked the code, and the preteos10 formulation of the equation of state uses just the sqrt of the salinity (not the abs). In the code Dens%rho(tau) is calculated just before, and the crash happens when calculating Dens%rho(taup1). My guess is that this time step instability is related with a velocity (maybe vertical?), and that an extra diffusivity could help with this.
The rivermix code has an option for enhaced diffusivity in the vertical (function river_kappa) that is not present in the basal parameterization. It may be a good idea to include this functionality.

**Comment by pedrocol** [comment]
There is no issue with the new parameterization, it must have been some faulty node and is solved just be re-running the simulation. Randomly it started crashing at the same month in years3 and 4 (october), and then in winter months. I'm running now with the standard time step, and every time it crash I resubmit the job as many times as needed until the job is completed. I'm running 1 month segments, but besides this there is no other issue. I confirm no extra diffusivity was added in any segment of the runs.

**Comment by aekiss** [comment]
Ah, well that explains why it was a segfault. In future we should report these to NRI - our big model runs are sensitive bad-node detectors and they can reboot bad nodes so we're not treading on a minefield.

To save all that babysitting you could use this payu feature to automatically sweep and resubmit when low-level errors (like segfaults) occur:
https://github.com/COSIMA/01deg_jra55_iaf/blob/4cacc1708f223a23d4262092bfb5fc9f19eb9240/config.yaml#L71-L74
https://github.com/COSIMA/01deg_jra55_iaf/blob/master/resub.sh
Increase `MAX_RESUBMISSIONS` to have more attempts before giving up.

**Comment by StephenGriffies** [comment]
Great to know it is not the code. I suspect it is on the edge of memory.  Perhaps add more nodes.  Otherwise, just let the payu feature do the nursing.

**Comment by pedrocol** [comment]
The run went just fine just by resubmitting it when there was a crush, the resub script was very useful. Thanks a lot to both of you! I'm closing the issue
