### ISSUE TITLE
T/S diagrams

### ISSUE THREAD

**Issue by adele-morrison** [pedrocol/basal_mom5-collaborative-project#62]
Make regional T/S diagrams. Is the basal melt simulation closer to obs? How much ISW do we get?

The issue on this using the old simulations is https://github.com/pedrocol/basal_mom5-collaborative-project/issues/30.

**Comment by adele157** [comment]
Obs comparison from https://doi.org/10.1029/2018JC014907:
![](https://user-images.githubusercontent.com/62230733/203470090-b085e20a-226c-47fc-96ca-32451b4973e8.png)

Maybe Hannah if you do the Amundsen comparisons again, you could repost the relevant obs T/S diagrams for that also.

**Comment by hrsdawson** [comment]
Before doing the comparison to observations,  here's a histogram plot in T-S space for the three simulations along the continental shelf from year 10 (only T-S points shallower than 1000m). In both the basal and icb gade simulations we get less of the fresh surface waters, as expected. We're also getting ISW in both simulations, but with some unrealistically cold temps too. 

<img width="1510" alt="Screenshot 2023-08-18 at 4 44 05 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/9506f805-792d-4356-9ecc-c3a9f71e9a82">

These cold temps originate from different locations along the shelf, but primarily close to ice shelves in the West Antarctic region. Plot shows locations where minimum temp <=-2.5 degrees at any depth during year 10 (masked to continental shelf).


<img width="1530" alt="Screenshot 2023-08-18 at 5 02 23 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/9bec8c8b-0045-4e01-975f-5797c2c70992">

**Comment by pedrocol** [comment]
The cold temperature values are not necessarily unrealistic, since your freezing definition does not consider pressure effects. It would be interesting to see in the same plot the freezing point temperature at 1000m depth

**Comment by hrsdawson** [comment]
@pedrocol I made a mistake in the plot above - thought I was just showing shelf waters, but I'd included deep off-shelf waters too. I've remade the plot for just the shelf  (<1000m) and there is very little change from above. The freezing point temp for 1000 dbar is now included in red. 

<img width="1360" alt="Screenshot 2023-08-23 at 6 47 56 pm" src="https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/e18acf9c-9f4a-4ada-bd4c-4ac02b4ab663">

**Comment by hrsdawson** [comment]
Some regional T-S diagrams. T-S points have been interpolated onto 50m vertical spacing from surface to 1000m in these plots. Freezing point at surface and 1000 dbar are shown in grey and red respectively. Basal Gade and ICB Gade are similar to each other in T-S space, with ISW in both simulations. In some regions (Amundsen Sea), there's a lot of very cold ISW. In the Weddell Sea we end up with more denser waters in the ICB Gade simulation than in the control and Basal Gade simulations.  

**Region map:**
![Screenshot from 2023-08-24 07-32-15](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/eeed1828-5158-4a11-a2c9-5ed9e4e7e663)
**Cape Darnley:**
![Screenshot from 2023-08-24 07-32-26](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/46ff1d93-1220-4ae7-b026-4d9967daeea4)
**East Antarctica:**
![Screenshot from 2023-08-24 07-32-37](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/dd467590-273f-4b53-92d9-0e1993b3dc88)
**SW Ross Sea:**
![Screenshot from 2023-08-24 07-32-46](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/32c189b6-6ebf-4f36-9d42-fc650050169a)
**Amundsen Sea:**
![Screenshot from 2023-08-24 07-32-56](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/f0f2ec40-ef03-4dee-a202-cc56b804d054)
**Bellingshausen Sea:**
![Screenshot from 2023-08-24 07-37-28](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/e61f5d65-3f21-4918-bc53-6894bd052eed)
**Weddell Sea:**
![Screenshot from 2023-08-24 07-33-13](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/a9f78f60-73c0-4440-b817-5b54fdd452e2)

**Comment by hrsdawson** [comment]
> Obs comparison from https://doi.org/10.1029/2018JC014907: 

Here's the **control** comparison plot:
![Screenshot from 2023-08-24 07-42-46](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/1a01f85c-ee52-4225-91e5-f3a3e1edef87)

And for the **Basal Gade** simulation:
![Screenshot from 2023-08-24 07-42-22](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/06b434c7-7792-48c1-9e9e-40cf107234df)

I'm not posting the ICB Gade comparison here as it looks very similar to the Basal Gade figure above. I find it quite hard to tell if we're getting any closer to observations from these figure comparisons (aside from forming some ISW). I wonder if it's worth trying to get the seal MEOP data from the shelf and comparing the simulations to that?

**Comment by hrsdawson** [comment]
> Maybe Hannah if you do the Amundsen comparisons again, you could repost the relevant obs T/S diagrams for that also.

Here's the Amundsen Sea plots - control and simulations on top row, observations below. In the top two plots, we get a shift to colder temperatures in both simulations with a broader spread in T-S space. The ICB Gade simulation has saltier water than in the Basal Gade simulation (too saline compared to the obs). Paper for reference:  https://www.nature.com/articles/s41467-022-28751-5

![Screenshot from 2023-08-24 07-51-23](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/c8243361-b089-4d30-832e-1f512756110b)

![Screenshot from 2023-08-24 07-58-44](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/e73ebde0-20dd-4109-97c2-7ed46c44cd16)

Here it looks like the two basal melt simulations are getting further from the observations. We're getting colder and saltier water than observed. I've included T-S from across the last year of the simulation in this comparison, whereas the observations are taken mostly from January to March. If I restrict the comparison to only Jan-March temp-salinity values, we still get this denser water forming in the two simulations. Paper for reference: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JC015133  

![Screenshot from 2023-08-24 07-59-08](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/c3975b62-ffea-415b-aab1-520bb9a36620)

**Comment by hrsdawson** [comment]
Updated T-S histograms with the new simulation (Basal No Gade and No ICB). We don't get the very cold waters when using $T_{basal}$ equal to  $T_{insitu}$ with calving flux inserted at the surface as runoff. 

![Screenshot from 2023-11-02 10-29-11](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/f1266933-cba9-46de-b142-8a7d4fc4680e)

**Comment by hrsdawson** [comment]
Here's an option for Figure 5 showing T-S along the shelf compared to WOA18 along the shelf. I haven't shown $Basal_{NoGade}$ for now which doesn't produce any ISW. The obs are a bit sparse, particularly if we look regionally. Do you think we should try MEOP for obs?

![Figure05_T-S_diag_circumantarctic (1)](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/75f0a212-65ff-4087-89d6-954b7a754675)


I do feel this circum-Antarctic view masks some of the regional differences, see below. I picked these regions to cover major ice shelves and to represent dense, fresh, and warm shelf regimes. 

![Figure05_T-S_diag_regional (1)](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/62230733/64a82913-f77f-4a1b-9d28-4413a33daff6)

**Comment by hrsdawson** [comment]
New issue using the updated simulations is here https://github.com/pedrocol/basal_mom5-collaborative-project/issues/85
