### ISSUE TITLE
Sea ice changes

### ISSUE THREAD

**Issue by adele-morrison** [pedrocol/basal_mom5-collaborative-project#64]
*Time series of sea ice extent and volume.
*Maps of concentration and thickness change.
*Comparison with obs.

Previous issue using old simulations is https://github.com/pedrocol/basal_mom5-collaborative-project/issues/33.

**Comment by aekiss** [comment]
Should also plot `frazil` and `congel` for comparison with `frazil_3d_int_z` and `mh_flux` in the heat budget - see https://github.com/pedrocol/basal_mom5-collaborative-project/issues/66

**Comment by aekiss** [comment]
I've largely rewritten `notebooks/seaice/seaice.ipynb` to use the new experiments and fix several mistakes. The plots below are from [this commit](https://github.com/pedrocol/basal_mom5-collaborative-project/blob/9169f2afff24a7ffb42c67f5e17b55d29cdc73fc/notebooks/seaice/seaice.ipynb).

**Comment by aekiss** [comment]
Here are timeseries of the sea ice volume over the full length of the experiments, integrated over the full Antarctic or just the shelf (onshore of 1000m isobath). They stabilise after about 3 years, so in the later plots I use 1903-1909 (inclusive) for climatologies.

There are two pairs: 
1. without Gade: `Control` and `BasalNoGade_NoIcb` are nearly identical
2. with Gade: `BasalGade_NoIcb` and `BasalGade_YesIcb` have more ice than without Gade

The difference between these pairs is more pronounced on the shelf. Adding iceberg spreading (`BasalGade_YesIcb`) further increases the sea ice volume in the Gade case, especially on the shelf.
![download](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/e806b719-4e95-4273-8ce3-ee0bce404285)
![download-1](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/54f114b1-6007-4d96-8930-b8d15dcfb652)

**Comment by aekiss** [comment]
These are the 1903-1909 monthly climatologies of sea ice extent (i.e. area with concentration over 15%), compared to observations over the RYF forcing period (1 May 1990 - 30 April 1991).
Differences between the 4 experiments are much smaller than the bias relative to obs. Model sea ice is too low in the Feb minimum, rises too soon to a peak that's close to obs but too early (Aug instead of Sept), then falls off initially too gradually and then too steeply. `BasalGade_YesIcb` has the smallest bias, but is not significantly improved over the others.

![download-2](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/67a7a822-5f58-41e4-b3c8-d3ec64a3c27e)

**Comment by aekiss** [comment]
The 1903-1909 mean thickness in `BasalGade_YesIcb` (middle column) is mainly increased on the West Antarctic shelves. The pattern in `BasalGade_NoIcb` (left) is similar but weaker. As seen in the volume timeseries, `BasalNoGade_NoIcb` (right) is nearly identical to `Control`, but with slight thinning in the Amundsen-Bellingsausen seas.

Annual mean patterns (top row) are similar to those in Feb (middle row) and Sept (bottom). Thinning is mostly in winter (Sept), whereas thickening seems less dependent on season. May need to look at more months to confirm this.

![download-3](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/c2d48658-86bf-440b-871c-60f478ff682f)
![download-5](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/91b08554-7a6c-42d1-8243-fecb1e4b9541)
![download-6](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/77528489-876e-4de0-b1b6-046035c247ac)

**Comment by aekiss** [comment]
The 1903-1909 sea ice concentration differences seem more seasonal than the thickness differences. As for thickness, `BasalGade_NoIcb` (left) is similar to `BasalGade_YesIcb` (middle) but weaker.
Increases in this pair occur mostly in the Weddell, eastern Ross and Prydz shelves and mostly in summer (middle row).
Reductions in this pair occur mostly in winter (bottom row) and off the shelf, mostly near the ice edge, but there's also a strong reduction near the Ross shelf edge in `BasalGade_YesIcb`.
Again `BasalNoGade_NoIcb` (right) is nearly identical to `Control`, with a different pattern.

![download-4](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/052683b5-c777-4866-a3d8-ce7a89cd1534)
![download-7](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/e762d169-3fa6-4a70-8f18-0d969a594aba)
![download-8](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/b0c4d4d6-8e9b-406e-9ae4-211653104259)

**Comment by aekiss** [comment]
Sea ice concentration biases relative to observations over the RYF forcing period are very similar in the 4 experiments.
February has a pronounced low bias, especially in the Weddell Sea. This is very subtly better in `BasalGade_YesIcb` than the others.
September biases are smaller and mostly in the ice edge. `BasalGade_YesIcb` looks a little worse than `Control` in this season, and has a negative bias off the shelf in the eastern Ross that doesn't appear in the other cases.

![download-13](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/ca112ae9-120b-497c-ae87-5be4e36b856e)
![download-14](https://github.com/pedrocol/basal_mom5-collaborative-project/assets/31054815/f6726135-9291-491e-9551-3ccc57948b9f)

**Comment by aekiss** [comment]
Closing this issue because it uses the old simulations. See new sea ice issue https://github.com/pedrocol/basal_mom5-collaborative-project/issues/81
